import stack

my_stack1 = stack.Stack()
my_stack2 = stack.Stack([1, 2, 3, 4])
my_stack3 = stack.Stack(1)

# Test push()
my_stack1.push(1)
my_stack1.push(2)
my_stack1.push((3, 4))
my_stack1.push([5, 6])
my_stack1.print_stack()
my_stack3.print_stack()
print()
print("Expected: 6 5 4 3 2 1 1")
print("-----")

# Test peek()
print(my_stack2.peek())
print("Expected 4")
print(my_stack2.peek())
print("Expected 4")
print("-----")

# Test pop()
print(my_stack1.pop())
print("Expected 6")
print(my_stack1.pop())
print("Expected 5")
print("-----")

# Test isEmpty() and clear_stack()
print(my_stack1.is_empty())
print("Expected: False")
my_stack1.clear_stack()
print(my_stack1.is_empty())
print("Expected: True")
print("-----")

# Test contains()
print(my_stack2.contains(1))
print("Expected: True")
print(my_stack2.contains(9))
print("Expected: False")
print("-----")

# Test __iter__()
for i in my_stack2:
    print(i, end=" ")
print()
print("Expected: 4 3 2 1")
print("-----")

# Test reverse()
my_stack2.print_stack()
print()
my_stack2.reverse()
my_stack2.print_stack()
print()
print("Expected: 1 2 3 4")
print("-----")
