from queue import Queue

queue1 = Queue()
queue2 = Queue([1, 2, 3, 4])
queue3 = Queue(1)

# Test push()
queue1.push(1)
queue1.push(2)
queue1.push((3, 4))
queue1.push([5, 6])
queue1.print_queue()
queue3.print_queue()
print()
print("Expected: 1 2 3 4 5 6 1")
print("-----")

# Test peek()
print(queue2.peek())
print("Expected 1")
print(queue2.peek())
print("Expected 1")
print("-----")

# Test pop()
print(queue1.pop())
print("Expected 1")
print(queue1.pop())
print("Expected 2")
print("-----")

# Test isEmpty() and clear_queue()
print(queue1.is_empty())
print("Expected: False")
queue1.clear_queue()
print(queue1.is_empty())
print("Expected: True")
print("-----")

# Test contains()
print(queue2.contains(1))
print("Expected: True")
print(queue2.contains(9))
print("Expected: False")
print("-----")

# Test __iter__()
for i in queue2:
    print(i, end=" ")
print()
print("Expected: 1 2 3 4")
print("-----")

# Test reverse()
queue2.print_queue()
print()
queue2.reverse()
queue2.print_queue()
print()
print("Expected: 4 3 2 1")
print("-----")
